#!/bin/bash
USAGE="$0"' [-p|--prefix $PREFIX]
Installs daily-backup by copying the files to the directories under prefix, which defaults
to an empty string (leading to system directories)'

# Defaults
PREFIX=""

# Argparse
SHORT="p:"
LONG="prefix:"
OPTS="$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")"
! [ "$?" = 0 ] && echo "$USAGE" 1>&2 && exit 1
eval set -- "$OPTS"

while [[ "$#" -gt 0 ]]
do
    case "$1" in
        -p|--prefix)
            PREFIX="$2"
            shift
            shift
            ;;
        --)
            shift
            ;;
        *)
            { echo "ERROR: Unexpected param '$2'" ; echo "$USAGE" ; } 1>&2
            exit 1
            ;;
    esac
done

# Script
set -e

# Executables
install -D "bash/entrypoint" "$PREFIX/usr/bin/daily-backup"
install -D "bash/daily-backup-run" "$PREFIX/usr/lib/daily-backup/daily-backup-run"
install -D "bash/daily-backup-upload" "$PREFIX/usr/lib/daily-backup/daily-backup-upload"
install -D "bash/daily-backup-launch" "$PREFIX/usr/lib/daily-backup/daily-backup-launch"
install -D "bash/daily-backup-send-email" "$PREFIX/usr/lib/daily-backup/daily-backup-send-email"
install -D "bash/daily-backup-version" "$PREFIX/usr/lib/daily-backup/daily-backup-version"
install -D "python/daily-backup-upload-backblaze-b2.py" "$PREFIX/usr/lib/daily-backup/daily-backup-upload-backblaze-b2.py"

# Systemd templates
install -D "systemctl/daily-backup.service" "$PREFIX/usr/share/doc/daily-backup/systemd-templates/daily-backup.service"
install -D "systemctl/daily-backup.timer" "$PREFIX/usr/share/doc/daily-backup/systemd-templates//daily-backup.timer"

# Config examples
install -D "config/env.example" "$PREFIX/usr/share/doc/daily-backup/env.example"
