#!/bin/bash
USAGE="$0"' [-p|--prefix $PREFIX]
Installs daily-backup by copying the files to the directories under prefix, which defaults
to an empty string (leading to system directories)'

# Defaults
PREFIX=""

# Argparse
SHORT="p:"
LONG="prefix:"
OPTS="$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")"
! [ "$?" = 0 ] && echo "$USAGE" 1>&2 && exit 1
eval set -- "$OPTS"

while [[ "$#" -gt 0 ]]
do
    case "$1" in
        -p|--prefix)
            PREFIX="$2"
            shift
            shift
            ;;
        --)
            shift
            ;;
        *)
            { echo "ERROR: Unexpected param '$2'" ; echo "$USAGE" ; } 1>&2
            exit 1
            ;;
    esac
done

# Script
set -e

mkdir -p "$PREFIX/usr/bin/"
mkdir -p "$PREFIX/usr/lib/daily-backup/"
mkdir -p "$PREFIX/etc/systemd/system/"

cp "bash/entrypoint" "$PREFIX/usr/bin/daily-backup"
chmod +x "$PREFIX/usr/bin/daily-backup"

cp "bash/daily-backup-run" "$PREFIX/usr/lib/daily-backup/daily-backup-run"
chmod +x "$PREFIX/usr/lib/daily-backup/daily-backup-run"

cp "bash/daily-backup-upload" "$PREFIX/usr/lib/daily-backup/daily-backup-upload"
chmod +x "$PREFIX/usr/lib/daily-backup/daily-backup-upload"

cp "bash/daily-backup-launch" "$PREFIX/usr/lib/daily-backup/daily-backup-launch"
chmod +x "$PREFIX/usr/lib/daily-backup/daily-backup-launch"

cp "bash/daily-backup-send-email" "$PREFIX/usr/lib/daily-backup/daily-backup-send-email"
chmod +x "$PREFIX/usr/lib/daily-backup/daily-backup-send-email"

cp "bash/daily-backup-version" "$PREFIX/usr/lib/daily-backup/daily-backup-version"
chmod +x "$PREFIX/usr/lib/daily-backup/daily-backup-version"

cp "python/daily-backup-upload-backblaze-b2.py" "$PREFIX/usr/lib/daily-backup/daily-backup-upload-backblaze-b2.py"
chmod +x "$PREFIX/usr/lib/daily-backup/daily-backup-upload-backblaze-b2.py"

cp "systemctl/daily-backup.service" "$PREFIX/etc/systemd/system/daily-backup.service"
cp "systemctl/daily-backup.timer" "$PREFIX/etc/systemd/system/daily-backup.timer"

