#!/bin/bash
USAGE="$0"' [-t TO_EMAIL] [-a ATTACHMENT_FILE] [-w WAIT_BETWEEN] [-m MAX_RETIRES]
Uses MailGun to send an email with the results of the daily backup.
Depends on env var DAILY_BACKUP_MAILGUN_API_KEY and DAILY_BACKUP_MAILGUN_DOMAIN.

[-t TO_EMAIL]        -> The destinatary email.
[-a ATTACHMENT_FILE] -> The file to attach.
[-w WAIT_BETWEEN]    -> Time to wait between two attempts to send the email. Default: 30.
[-m MAX_RETIRES]     -> Max retries to send the email. Default: 30.'

# 

# getopt
SHORT='f:t:a:w:m:'
OPTS="$(getopt --options $SHORT --name "$0" -- "$@")"
! [ "$?" = 0 ] && echo "$USAGE" 1>&2 && exit 1
eval set -- "$OPTS"

# Defaults
WAIT_BETWEEN='30'
MAX_RETRIES='100'

# Parses params
while [[ "$#" -gt 0 ]]
do
    key="$1"
    case "$key" in
        -t)
            TO_EMAIL="$2"
            shift
            shift
            ;;
        -a)
            ATTACHMENT="$2"
            shift
            shift
            ;;
        -w)
            WAIT_BETWEEN="$2"
            shift
            shift
            ;;
        -m)
            MAX_RETRIES="$2"
            shift
            shift
            ;;
        --)
            shift
            ;;
        *)
            echo "$USAGE" 1>&2
            exit 1
    esac
done

# Ensures params
for x in TO_EMAIL ATTACHMENT WAIT_BETWEEN MAX_RETRIES DAILY_BACKUP_MAILGUN_API_KEY DAILY_BACKUP_MAILGUN_DOMAIN
do
    if [ -z "${!x}" ]
    then
        { echo "ERROR: Missing $x" ; echo "$USAGE" ; } 1>&2
        exit 1
    fi
done

# Helper functions
function subject() { echo "Your daily backup script ended." ; }
function text() { echo -e "$(subject)\n\nSee attached file for the tar log :)!" ;}

# Script
echo "Sending email..."
SUCCESS="0"
ATTEMPT='1'
while [ "$SUCCESS" = 0 ] && [[ "$ATTEMPT" -le "$MAX_RETRIES" ]]
do
    echo "Attempt: $ATTEMPT"
    if curl \
           --user "api:$DAILY_BACKUP_MAILGUN_API_KEY" \
           -F "from=Daily Backup <mailgun@${DAILY_BACKUP_MAILGUN_DOMAIN}>"\
           -F "to=$TO_EMAIL" \
           -F "subject=$(subject)" \
           -F "text=$(text)" \
           -F "attachment=@${ATTACHMENT}" \
           "https://api.mailgun.net/v3/${DAILY_BACKUP_MAILGUN_DOMAIN}/messages"
    then
        SUCCESS='1'
    else
        ATTEMPT="$((ATTEMPT+1))"
        echo "Failed! Sleeping..."
        sleep "$WAIT_BETWEEN"
    fi
done
