#!/bin/bash
USAGE="$0"' command [options...]
Entrypoint for daily backup.

Command can be one of:
- run
- launch
- send-email
- upload
- upload-backblaze-b2
- version
- print-stats

Use `command --help` for seeing the helper of each command.'

COMMAND="$1"
shift

case "$COMMAND" in
    run)
        /usr/lib/daily-backup/daily-backup-run "$@"
        ;;

    launch)
        /usr/lib/daily-backup/daily-backup-launch "$@"
        ;;

    send-email)
        /usr/lib/daily-backup/daily-backup-send-email "$@"
        ;;

    upload)
        /usr/lib/daily-backup/daily-backup-upload "$@"
        ;;

    upload-backblaze-b2)
        /usr/lib/daily-backup/daily-backup-upload-backblaze-b2.py "$@"
        ;;

    version)
        /usr/lib/daily-backup/daily-backup-version "$@"
        ;;

    print-stats)
        /usr/lib/daily-backup/daily-backup-print-stats "$@"
        ;;

    *)
        { echo "ERROR: Unkown command $COMMAND" ; echo "$USAGE" ; } 1>&2
        exit 1
        ;;
esac
